export const articleNavItems = [
  { label: 'Gateway Systems', link: '/articles/gateway-systems/' },
  { label: 'The API Front Door', link: '/articles/the-api-front-door/' },
  { label: 'Service Discovery', link: '/articles/service-discovery/' },
  { label: 'Observability by Signal', link: '/articles/observability-by-signal/' },
  { label: 'Federated API Security', link: '/articles/federated-api-security/' },
  { label: 'Workflows that Remember', link: '/articles/workflows-that-remember/' },
  { label: 'Lightweight Queueing', link: '/articles/lightweight-queueing/' },
  { label: 'Eventing with CloudEvents', link: '/articles/eventing-with-cloudevents/' },
  { label: 'Queueing Matters', link: '/articles/queueing-matters/' },
  { label: 'The Shape of Traffic', link: '/articles/the-shape-of-traffic/' },
  { label: 'Decoupled by Design', link: '/articles/decoupled-by-design/' },
  { label: 'Open Source Sovereignty', link: '/articles/open-source-sovereignty/' },
  { label: 'OpenAPI-first MCP', link: '/articles/openapi-first-mcp/' },
];